[id]
from = "weapon.base"
cid = "weapon.minigun"

[visibility]
size = [128, 64]

[image]
name = "minigun"
rotate_anchor = [35, 30]

[behaviour]
mag_size = 80
reload_time = 3
recoil_time = 0.02
inaccuracy = 0.01093606
muzzle_velocity = 1600

[bullet]
type = "<bullet.minigun>"

[sound]
preset = "minigun"
