changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bugs? No more! 🐞
      labels:
        - bug
    - title: Inexplicable code? Should be better now 📝
      labels:
        - documentation
    - title: Community Contributions 🤝
      labels:
        - good first issue
        - help wanted
    - title: Other Changes 🛠
      labels:
        - "*"
