import typing as tp
from amoginarium.shared.utility import Vec2
from .collision_event import CollisionCallback

class CollisionManager:
    def __init__(self, base_cell_size: float = 100.0, level_dividers: list[int] = None) -> None: ...
    def add_group(self, max_level: int, is_static: bool = False) -> int: ...
    def clear_all_entities(self) -> None: ...
    def register_entity(self, group_id: int, instance: tp.Any, pos: Vec2, size: Vec2, centered: bool = False) -> int: ...
    def delete_entity(self, group_id: int, entity_id: int) -> None: ...
    def update_entity(self, group_id: int, entity_id: int, pos: Vec2 | None = None, size: Vec2 | None = None, centered: bool | None = None) -> None: ...
    def create_relation(self, group_a_id: int, group_b_id: int, cb_a: CollisionCallback | None, cb_b: CollisionCallback | None) -> None: ...
    def calculate_all_collisions(self) -> None: ...