[id]
from = "dummy.missile.multi_stage"
cid = "missile.rpg"

[visibility]
size = [64, 16]

[trace]
color = [[255, 255, 255, 100]]  # either one or two colors
length = 300
width_mult = 0.3  # trace width multiplier


[image]
name = "rpg_rocket"
#mirror = "x"

[behaviour]
hp = 0.5
ttl = 6  # rpg fuzes after 4-6 seconds with no target
weight = 5  # knockback
mass = 10  # aerodynamics
base_damage = 30
#invincibility_offset = 0.1

[explosion]
radius = 128
damage = 80

[rudder]
size = 100
max_angle = 0.01

[motor]
start = [0.3, 0]
launch = [0.2, 80_000, 50]
accel = [0.5, 25_000, 10]
