name: Blank issue
description: Create a new issue from scratch
projects: [ "Nilusink/3" ]
body:
  - type: textarea
    id: description
    attributes:
      placeholder: Type your description here
    validations:
      required: true
