"""
Implement 2D Kalman Filter tracking.

Path: amoginarium/logic/entities/_weaponry/templates/_sensors/ckalman_track.pyi
Project: amoginarium
Created: 22.05.2026
Authors: Nilusink
"""

class KalmanTrack2D:
    def reset(self) -> None:  ...
    def initialize(self, x: float, y: float) -> None: ...
    def predict(self, dt: float) -> None: ...
    def update(self, mx: float, my: float) -> None: ...
    def step(self, mx: float, my: float, dt: float) -> None: ...
    def get_position(self) -> tuple[float, float]: ...
    def get_velocity(self) -> tuple[float, float]: ...
    def get_acceleration(self) -> tuple[float, float]: ...
    def predict_future_position(self, t: float) -> tuple[float, float]: ...
    def get_speed(self) -> float: ...
