[id]
from = "dummy.bullet.base"
cid = "bullet.sky_shield"

[visibility]
size = 18

[trace]
color = [[255, 80, 40], [255, 100, 60]]
length = 300

[behaviour]
weight = 1.5
base_damage = 30
visibility_offset = 0.08

[cluster]
depth = 1
amount = 11
spread = 1.5
fuze_ttl_mult = 0.02
step_size_mult = 0.3
step_explosion_size = 10
last_step_ttl = 0.7

[fuze.0]
type = "proximity"
distance = 128
function_delay = 0.5
