graph RL

    subgraph Group1 [" "]
        CollisionExceptions
        CollisionType
        EntityChildViable
        GameCollisions
    end

    subgraph Group2 [" "]
        HitboxTypes
    end

    subgraph Group3 [" "]
        BaseGroup
        LogicGroup
        _Bullets
        _FrictionXAffected
        _GravityAffected
        _Players
        _Updated
        _Walls
    end

    subgraph Group4 [" "]
        BaseLogicEntity
        CollisionLogicEntity
        DebugCircleEntity
        DebugPolygonEntity
        DebugRectangleEntity
        LogicGameEntity
        PositionedLogicEntity
    end

    PositionedLogicEntity --> BaseLogicEntity
    DebugCircleEntity --> PositionedLogicEntity
    DebugPolygonEntity --> PositionedLogicEntity
    DebugRectangleEntity --> PositionedLogicEntity
    CollisionLogicEntity --> PositionedLogicEntity
    LogicGameEntity --> CollisionLogicEntity
    BaseGroup --> LogicGroup
    _Bullets --> BaseGroup
    _Players --> BaseGroup
    _Walls --> BaseGroup
    _FrictionXAffected --> BaseGroup
    _GravityAffected --> BaseGroup
    _Updated --> BaseGroup