[id]
from = "dummy.bullet.base"
cid = "bullet.cram"

[visibility]
size = 15  # or list of x, y

[trace]
color = [[255, 80, 40], [255, 100, 60]]  # either one or two colors
color_time = 1.5
length = 300
show = true
fade = true
width_mult = 1  # trace width multiplier

[image]
name = "bullet"
mirror = "x"

[behaviour]
hp = 1
ttl = 2
weight = 5
base_damage = 15
visibility_offset = 0
invincibility_offset = 0

[explosion]
radius = -1
damage = 0

[cluster]
depth = 0
amount = 0
spread = 0.8
fuze_ttl_mult = 0.5
fuze_dist = -1
step_size_mult = 1
step_inertia = 0
step_explosion_size = 10
last_step_ttl = -1
bullet_type = "<dummy.bullet.base>"  # leaving this out will make self as cluster bullet type, brackets (<>) required!

