[id]
from = "turret.rideable.calculated"
cid = "turret.rideable.gps_guided"

[visibility]
size = [128, 128]
layer = 3

[image]
name = "skyshield_base"

[behaviour]
turn_speed = 1.57
max_error = 6
airburst_munition = false

[engagement]
ignore_solution = true  # ignore ballistic calculations for launch OK
valid_angles = [3.71, 5.71]
min_range = 150
max_range = 3000

[target]
taps = 1

[weapon]
type = "<weapon.gps_guided>"
position_offset = [0, -8]
#static_facing = -1.57 # - pi/2

[passenger]
visible = false
offset = [0, 0]
