[id]
from = "bullet.mortar"
cid = "bullet.mortar.cluster"

[cluster]
depth = 2
amount = 3
spread = 0.6
step_size_mult = 1
step_explosion_size = 0
last_step_ttl = 3

[fuze.0]
type="ttl_mult"
mult = 0.7

#[fuze.0]
#type = "alt"  # height above ground (must be above height to arm first)
#height = 500
