[id]
from = "turret.static.base"
cid = "turret.static.mortar"

[visibility]
#size = [23, 24]
size = [34.5, 36.0]

[image]
name = "mortar_turret_base"

[behaviour]
max_hp = 90
turn_speed = 0.3
facing_angle = -1.57  # facing up
max_error = 0.05
allow_static_target = true

[engagement]
aim_type = "high"
min_range = 550
max_range = 3000

[weapon]
type = "<weapon.mortar>"
position_offset = [0, -13]

[sensors.0]
type = "<sensor.radar>"
detection_range = 2500
min_rcs = 0.01

